sudo: required
dist: trusty
language: python

addons:
    apt:
        packages:
            - astyle
            - xsltproc
            - libxml2
            - libxml2-dev
            - gcc
            - wget

before_install:
    - wget http://131.123.42.38/lmcrs/beta/srcML-Ubuntu14.04-64.deb
    - sudo dpkg -i srcML-Ubuntu14.04-64.deb

install:
    - sudo python setup.py -q install
